version: '3.8'
services:
  api:
    build: .
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DEPLOY=http://localhost:3000
      - TOKENMERCADOPAGO=TEST-7700540102476059-042908-2398588a69264c6c2ffb4421e7abe70a-1791514408
      - STRIPE_SECRET_KEY=sk_test_51P9ruCEwWQ681LTETaIYlq6Y1DqkAAUNTUNs5WbsQyXME0UBv83HlamxhSz6NveaVIwh57Yfds5seUZ9LloqNuZU00yFrNooUk
      - STRIPE_WEBHOOK_SECRET=whsec_M3dxqAJJafNr5P5eOez4gHlgOsWXDNXN

    # volumes:
    #   - ./:/usr/src/app
  servidor:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=basededatos

    volumes:
      - ./data:/var/lib/postgresql/data
