services:
  servidor_node_express:
    container_name: servidor_node_express
    image: servidor_node_express:alpine
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/usr/src/app

    ports:
      - '3000:3000'

    env_file:
      - .env

    links:
      - servidor_ngrok_api
      - basededatos_docker
    depends_on:
      - basededatos_docker

  basededatos_docker:
    container_name: basededatos_docker
    image: postgres:alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_docker_Data:/var/lib/postgresql/data

  servidor_ngrok_api:
    container_name: servidor_ngrok_api
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    env_file:
      - .env
    command: start --all --config /etc/ngrok.yml
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml

volumes:
  postgres_docker_Data:
