# Usar una versión específica de Node.js para evitar cambios inesperados
FROM node:latest  

# Establecer el directorio de trabajo
WORKDIR /usr/src/app
 
 
# Copiar solo package.json antes de instalar dependencias
COPY package*.json ./

# Instalar dependencias con bun
RUN npm install

# Copiar el resto de los archivos después de instalar dependencias
COPY . .

# Usar el comando correcto para iniciar la app con bun
CMD ["npm", "run", "dev"]
